//! A module containing all Zotero document's type and their associated fields.

mod artwork;
pub use artwork::ArtworkData;
pub use artwork::ArtworkDataBuilder;
mod attachment;
pub use attachment::AttachmentData;
pub use attachment::AttachmentDataBuilder;
mod audio_recording;
pub use audio_recording::AudioRecordingData;
pub use audio_recording::AudioRecordingDataBuilder;
mod bill;
pub use bill::BillData;
pub use bill::BillDataBuilder;
mod blog_post;
pub use blog_post::BlogPostData;
pub use blog_post::BlogPostDataBuilder;
mod book_section;
pub use book_section::BookSectionData;
pub use book_section::BookSectionDataBuilder;
mod book;
pub use book::BookData;
pub use book::BookDataBuilder;
mod case;
pub use case::CaseData;
pub use case::CaseDataBuilder;
mod computer_program;
pub use computer_program::ComputerProgramData;
pub use computer_program::ComputerProgramDataBuilder;
mod conference_paper;
pub use conference_paper::ConferencePaperData;
pub use conference_paper::ConferencePaperDataBuilder;
mod dictionary_entry;
pub use dictionary_entry::DictionaryEntryData;
pub use dictionary_entry::DictionaryEntryDataBuilder;
mod document;
pub use document::DocumentData;
pub use document::DocumentDataBuilder;
mod email;
pub use email::EmailData;
pub use email::EmailDataBuilder;
mod encyclopedia_article;
pub use encyclopedia_article::EncyclopediaArticleData;
pub use encyclopedia_article::EncyclopediaArticleDataBuilder;
mod film;
pub use film::FilmData;
pub use film::FilmDataBuilder;
mod forum_post;
pub use forum_post::ForumPostData;
pub use forum_post::ForumPostDataBuilder;
mod hearing;
pub use hearing::HearingData;
pub use hearing::HearingDataBuilder;
mod instant_message;
pub use instant_message::InstantMessageData;
pub use instant_message::InstantMessageDataBuilder;
mod interview;
pub use interview::InterviewData;
pub use interview::InterviewDataBuilder;
mod journal_article;
pub use journal_article::JournalArticleData;
pub use journal_article::JournalArticleDataBuilder;
mod letter;
pub use letter::LetterData;
pub use letter::LetterDataBuilder;
mod magazine_article;
pub use magazine_article::MagazineArticleData;
pub use magazine_article::MagazineArticleDataBuilder;
mod manuscript;
pub use manuscript::ManuscriptData;
pub use manuscript::ManuscriptDataBuilder;
mod map;
pub use map::MapData;
pub use map::MapDataBuilder;
mod newspaper_article;
pub use newspaper_article::NewspaperArticleData;
pub use newspaper_article::NewspaperArticleDataBuilder;
mod note;
pub use note::NoteData;
pub use note::NoteDataBuilder;
mod patent;
pub use patent::PatentData;
pub use patent::PatentDataBuilder;
mod podcast;
pub use podcast::PodcastData;
pub use podcast::PodcastDataBuilder;
mod presentation;
pub use presentation::PresentationData;
pub use presentation::PresentationDataBuilder;
mod radio_broadcast;
pub use radio_broadcast::RadioBroadcastData;
pub use radio_broadcast::RadioBroadcastDataBuilder;
mod report;
pub use report::ReportData;
pub use report::ReportDataBuilder;
mod statute;
pub use statute::StatuteData;
pub use statute::StatuteDataBuilder;
mod thesis;
pub use thesis::ThesisData;
pub use thesis::ThesisDataBuilder;
mod tv_broadcast;
pub use tv_broadcast::TvBroadcastData;
pub use tv_broadcast::TvBroadcastDataBuilder;
mod video_recording;
pub use video_recording::VideoRecordingData;
pub use video_recording::VideoRecordingDataBuilder;
mod webpage;
pub use webpage::WebpageData;
pub use webpage::WebpageDataBuilder;
